console.log("Supermercado Hernan");
console.log("fideos soperos Arcor", "100 unidades");
console.log("fideos spaghetti Terrabusi", "150 unidades");
console.log("pure de tomates Mora", "200 unidades");
console.log("jugo Tang", "80 unidades");
console.log("galletitas Surtido Bagley", "300 unidades");
console.log("desodorante Axe", "180 unidades");
console.log("miel La Reina", "220 unidades");
console.log("arroz Gallo", "300 unidades");
console.log("lentejas Abadia", "140 unidades");
console.log("primer cambio");
